deploy:
  provider: rubygems
  api_key:
    secure: l6ekOcMsoJbWI9hV9KAnAlHaCycBmCan7srvvGfSX6JdEuByJf0RQemN1NJRi3UmnDLJ1YSQosSBsHvdQM3ooBHw0WN32EX7M/BeoSfOtga9AIM23uIPGcidN384y+JRU+ta8mnsOYqSF4PD7n3tvPrsXcVhU4Zsdi8RFcRbDhzSoLRXEHvcn1Dgik5G5jM9KbDjhJ/1jirW9CGH3CrGKfL0p2fqZn5kfcbKABOv5+tmi9oOij6IYdwsJd3O9D6oJuGs/h11M8Gld0lhdhxUj3qtSV3XpF6/ZVNvFEtO//bvQShqotb3dEBWyfnC8tiDHh9lOYV9stUhR4o0aHU2bm7SD3MyuEdy+OgoFMVZ5L7tH1B7f6ss8F9G2EmQQZgx4JPFv+D0It92kGnTSyqC3fGGuc8SwpVQIbfLAh88wj3mWi7cB4jrQnS4jVFmGEilA1kb6La0KKw5jJrkDTAKPotLBV/+45Gi++cY5+m0FUmi/h59Lw/IX9uvq6kraLYj/8kLEXQQHEhBs+0tWTkesxCmXCtJDflIMwYOvP+lfIdZxZR3phCEIl5U4WcNiNDAf/vJIDvs7YCd9Ny9Zgj/tu3wL4YReA6jslbYqQcxfnhC13vgguaCyTwhvJnVImQtiIZlvJIIynXBo6LDdc+fUReV4t5fTJ8FuCN9hQDGk24=
  on:
    tags: true
